### ISSUE TITLE
[BUG] 스토리북 오류

### ISSUE THREAD

**Issue by kmaledev** [TEAM-SUITS/Suits#130]
**Describe the bug🦟**

**이 버그를 발견하는 방법**
1. Go to 스토리북 실행 `npm run storybook`
2. See error

**원래는 어떻게 동작하나요?**
(버그가 없으면 원래 어떻게 작동해야 하는지 알려주세요.)
스토리북이 정상적으로 표시되어야 함.

**Screenshots**
<img width="1161" alt="Screen Shot 2021-04-26 at 11 44 42 PM" src="https://user-images.githubusercontent.com/72863748/116102484-b76e9300-a6e9-11eb-8744-e80fa3d7b70f.png">

**Additional context**
theme.styled.js 파일에서 props로 받는 theme을 제대로 읽어들이지 못해서 발생하는 것 같습니다.
이런 저런 것들을 수정해봤는데 아직 해결하지 못하고 있습니다.
아래는 에러 메시지에 표시되는 theme.styled.js 파일의 문제 코드입니다.
해결해보려고 계속 노력해보겠지만 혹시 원인을 아실 것 같으면 조언 부탁드립니다.
<img width="622" alt="Screen Shot 2021-04-26 at 11 45 15 PM" src="https://user-images.githubusercontent.com/72863748/116102709-e422aa80-a6e9-11eb-85cc-9cda0559b034.png">

**Comment by ahnanne** [comment]
- 해결하기는 했습니다..!
- 임시방편이고 스토리북 차원에서 해결할 수 있는 근본적인 해결책이 있겠지만... 당장에 컴포넌트를 확인하기는 해야 하니 우선은 아래와 같이 해결해보았습니다.
- 임시로 스토리북의 `preview.js`를 위한 global style을 하나 더 만들어서, 아래와 같이 props를 받아오는 부분에만 직접 컬러를 지정해주었습니다.

  ```css
    background-color: #FAFAFA;
    color: #101010;
  ```

**Comment by ahnanne** [comment]
- 재운님이 스토리북 공식 문서 참고하여 해결하셨습니다!
- https://github.com/TEAM-SUITS/Suits/pull/131 참고
