### ISSUE TITLE
feat: 비속어 필터링 api 제작

### ISSUE THREAD

**Issue by ahnanne** [TEAM-SUITS/Suits#9]
# ✨Feature Request

## 비속어 필터링 api 제작
- 욕설 및 비속어 필터링을 위한 api 제작 필요

**Comment by choi8686** [comment]
언제쯤 제작되나요?

**Comment by kmaledev** [comment]
팀원들이 욕설, 비속어에 익숙하지 않아서 시간이 많이 소요되고 있습니다.

**Comment by choi8686** [comment]
https://docs.google.com/document/d/1HHjUvUK4tXEGrpyEARLzAcoEbjEoTvs7WTOJx8BQJkY/edit

비속어 관련 리스트입니다.

**Comment by ahnanne** [comment]
감사합니다! 제공해주신 데이터 활용해서 빠른 시일 내에 제작하도록 하겠습니다😊

**Comment by ahnanne** [comment]
> https://docs.google.com/document/d/1HHjUvUK4tXEGrpyEARLzAcoEbjEoTvs7WTOJx8BQJkY/edit
> 
> 비속어 관련 리스트입니다.

안녕하세요~ 제공해주신 데이터 바탕으로 API 작성해봤는데, 혹시 필요하시다면 아래 파일 참고 부탁드립니다!
https://github.com/TEAM-SUITS/Suits/tree/develop/client/src/utils/badwordFilter
좋은 자료 제공해주셨는데 다른 작업들 먼저 진행하다보니 너무 오래 걸렸네요 ㅎㅎ;

[bad-words 라이브러리](https://www.npmjs.com/package/bad-words)가 이미 있더라구요! 저희는 직접 사용은 하지 않고 API 작성하는 데 참고만 하였지만, 한국어도 지원한다고 하니 제공해주셨던 데이터와 함께 사용해보시는 것도 좋을 것 같아요~
